### ISSUE TITLE
AutoATC clashes with SAM3 

### ISSUE THREAD

**Issue by JT8D-17** [mSparks43/XPlane-11-AutoATC-plugin#99]
When AutoATC (tested version 0.9.7.4) and Scenery Animation Manager (tested: 3.0.14) are installed at the same time, X-Plane crashes during startup.
Removing either plugin makes it work again.

GDB backtrace:
> (gdb) bt
#0  0x00007ffff6f15d22 in raise () at /usr/lib/libc.so.6
#1  0x00007ffff6eff862 in abort () at /usr/lib/libc.so.6
#2  0x00007ffe3a569e60 in sparx::crash_handler::handle_posix_sig(int, siginfo_t*, void*) ()
    at /media/X-Plane/X-Plane_Main/Resources/plugins/SAM/lin_x64/SAM.xpl
#3  0x00007ffff7217870 in <signal handler called> ()
    at /usr/lib/libpthread.so.0
#4  0x00007ffe9d963231 in  ()
#5  0x00007ffe731f7718 in  ()
#6  0x00007ffe73c07e98 in  ()
#7  0x00007ffe731f77e8 in  ()
#8  0x00007ffe73c08338 in  ()
#9  0x00007ffe73c09470 in  ()
#10 0x0000000629c79438 in  ()
#11 0x00007ffe73c08000 in  ()
#12 0x0000000000000000 in  ()

Log.txt:
[Log.txt](https://github.com/mSparks43/XPlane-11-AutoATC-plugin/files/8035702/Log.txt)

Looks like the TCAS overrides may be a cause.

**Comment by mSparks43** [comment]
confirmed, investigating now (think it is probably map layer related).

**Comment by mSparks43** [comment]
Hmmm, so it looks like it is SAM crashing when it reaches its PluginEnable section (TCAS overrides is the last thing AutoATC does before SAM starts to begin), I'll try and contact the author and find out why.
